class TypesUtils {
  TypesUtils._();

  static List<String> types = [
    'bool',
    'byte/int8',
    'short/int16',
    'int/int32',
    'long/int64',
    'float/float32',
    'double/float64',
    'BigDecimal',
    'String',
    'Date',
    'Time',
    'DateTime',
    'Enum',
  ];

  /*static const Map<String, String> _conditionsFieldBool = {
    'isTrue': 'none',
    'isFalse': 'none',
  };
  static const Map<String, String> _conditionsFieldIntegers = {
    'isEqualTo': 'number',
    'isNotEqualTo': 'number',
    'isLessThan': 'number',
    'isLessThanOrEqualTo': 'number',
    'isGreaterThan': 'number',
    'isGreaterThanOrEqualTo': 'number',
  };
  static const Map<String, String> _conditionsFieldDecimals = {
    'isEqualTo': 'decimal',
    'isNotEqualTo': 'decimal',
    'isLessThan': 'decimal',
    'isLessThanOrEqualTo': 'decimal',
    'isGreaterThan': 'decimal',
    'isGreaterThanOrEqualTo': 'decimal',
  };
  static const Map<String, String> _conditionsFieldString = {
    'minLength': 'number',
    'maxLength': 'number',
    'isUpper': 'none',
    'isLower': 'none',
    'isNull': 'none',
    'isNotNull': 'none',
    'regex': 'text',
  };
  static const Map<String, String> _conditionsFieldDate = {
    'isEqualTo': 'date',
    'isNotEqualTo': 'date',
    'isLessThan': 'date',
    'isLessThanOrEqualTo': 'date',
    'isGreaterThan': 'date',
    'isGreaterThanOrEqualTo': 'date',
    'isLessThanCurrentDate': 'none',
    'isLessThanOrEqualToCurrentDate': 'none',
    'isGreaterThanCurrentDate': 'none',
    'isGreaterThanOrEqualToCurrentDate': 'none',
    'isGreaterThanCurrentDateTime': 'none',
    'isGreaterThanOrEqualToCurrentDateTime': 'none',
    'isLessThanCurrentTimeMinusSeconds': 'number',
    'isLessThanOrEqualToCurrentTimeMinusSeconds': 'number',
    'isGreaterThanCurrentTimePlusSeconds': 'number',
    'isGreaterThanOrEqualToCurrentTimePlusSeconds': 'number',
    'isLessThanCurrentTimeMinusMinutes': 'number',
    'isLessThanOrEqualToCurrentTimeMinusMinutes': 'number',
    'isGreaterThanCurrentTimePlusMinutes': 'number',
    'isGreaterThanOrEqualToCurrentTimePlusMinutes': 'number',
    'isLessThanCurrentTimeMinusHours': 'number',
    'isLessThanOrEqualToCurrentTimeMinusHours': 'number',
    'isGreaterThanCurrentTimePlusHours': 'number',
    'isGreaterThanOrEqualToCurrentTimePlusHours': 'number',
    'isLessThanCurrentDateMinusDays': 'number',
    'isLessThanOrEqualToCurrentDateMinusDays': 'number',
    'isGreaterThanCurrentDatePlusDays': 'number',
    'isGreaterThanOrEqualToCurrentDatePlusDays': 'number',
  };
  static const Map<String, String> _conditionsFieldDateTime = {
    'isEqualTo': 'dateTime',
    'isNotEqualTo': 'dateTime',
    'isLessThan': 'dateTime',
    'isLessThanOrEqualTo': 'dateTime',
    'isGreaterThan': 'dateTime',
    'isGreaterThanOrEqualTo': 'dateTime',
    'isLessThanCurrentDateTime': 'none',
    'isLessThanOrEqualToCurrentDateTime': 'none',
    'isGreaterThanCurrentDateTime': 'none',
    'isGreaterThanOrEqualToCurrentDateTime': 'none',
    'isLessThanCurrentTimeMinusSeconds': 'number',
    'isLessThanOrEqualToCurrentTimeMinusSeconds': 'number',
    'isGreaterThanCurrentTimePlusSeconds': 'number',
    'isGreaterThanOrEqualToCurrentTimePlusSeconds': 'number',
    'isLessThanCurrentTimeMinusMinutes': 'number',
    'isLessThanOrEqualToCurrentTimeMinusMinutes': 'number',
    'isGreaterThanCurrentTimePlusMinutes': 'number',
    'isGreaterThanOrEqualToCurrentTimePlusMinutes': 'number',
    'isLessThanCurrentTimeMinusHours': 'number',
    'isLessThanOrEqualToCurrentTimeMinusHours': 'number',
    'isGreaterThanCurrentTimePlusHours': 'number',
    'isGreaterThanOrEqualToCurrentTimePlusHours': 'number',
    'isLessThanCurrentDateMinusDays': 'number',
    'isLessThanOrEqualToCurrentDateMinusDays': 'number',
    'isGreaterThanCurrentDatePlusDays': 'number',
    'isGreaterThanOrEqualToCurrentDatePlusDays': 'number',
  };

  static const Map<String, String> _conditionsFieldTime = {
    'isEqualTo': 'dateTime',
    'isNotEqualTo': 'dateTime',
    'isLessThan': 'dateTime',
    'isLessThanOrEqualTo': 'dateTime',
    'isGreaterThan': 'dateTime',
    'isGreaterThanOrEqualTo': 'dateTime',
    'isLessThanCurrentTime': 'none',
    'isLessThanOrEqualToCurrentTime': 'none',
    'isGreaterThanCurrentTime': 'none',
    'isGreaterThanOrEqualToCurrentTime': 'none',
    'isLessThanCurrentTimeMinusSeconds': 'number',
    'isLessThanOrEqualToCurrentTimeMinusSeconds': 'number',
    'isGreaterThanCurrentTimePlusSeconds': 'number',
    'isGreaterThanOrEqualToCurrentTimePlusSeconds': 'number',
    'isLessThanCurrentTimeMinusMinutes': 'number',
    'isLessThanOrEqualToCurrentTimeMinusMinutes': 'number',
    'isGreaterThanCurrentTimePlusMinutes': 'number',
    'isGreaterThanOrEqualToCurrentTimePlusMinutes': 'number',
    'isLessThanCurrentTimeMinusHours': 'number',
    'isLessThanOrEqualToCurrentTimeMinusHours': 'number',
    'isGreaterThanCurrentTimePlusHours': 'number',
    'isGreaterThanOrEqualToCurrentTimePlusHours': 'number',
  };*/

  /*static String inputConditionType({
    required String dateType,
    required String condition,
  }) {
    if (dateType == 'bool') {
      return _conditionsFieldBool[condition]!;
    } else if (dateType == 'short/int16' || dateType == 'byte/int8') {
      return _conditionsFieldIntegers[condition]!;
    } else if (dateType == 'long/int64' || dateType == 'int/int16') {
      return _conditionsFieldIntegers[condition]!;
    } else if (dateType == 'double/float64' || dateType == 'float/float32') {
      return _conditionsFieldDecimals[condition]!;
    } else if (dateType == 'String') {
      return _conditionsFieldString[condition]!;
    } else if (dateType == 'Date') {
      return _conditionsFieldDate[condition]!;
    } else if (dateType == 'DateTime') {
      return _conditionsFieldDateTime[condition]!;
    } else if (dateType == 'Time') {
      return _conditionsFieldTime[condition]!;
    }
    return '';
  }*/

  static List<String> conditions(String dataType) {
    final conditionsMap = {
      'list': [
        'isEmpty',
        'isNotEmpty',
        'lengthEquals',
        'lengthNotEquals',
        'lengthLessThan',
        'lengthLessThanOrEqualTo',
        'lengthGreaterThan',
        'lengthGreaterThanOrEqualTo',
      ],
      'listOfEntities': [
        'isEmpty',
        'isNotEmpty',
        'lengthEquals',
        'lengthNotEquals',
        'lengthLessThan',
        'lengthLessThanOrEqualTo',
        'lengthGreaterThan',
        'lengthGreaterThanOrEqualTo',
      ],
      'bool': ['isTrue', 'isFalse'],
      'short/int16': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
      ],
      'byte/int8': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
      ],
      'int/int32': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
      ],
      'long/int64': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
      ],
      'double/float64': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
      ],
      'BigDecimal': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
      ],
      'float/float32': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
      ],
      'String': [
        'isNotEmpty',
        'minLength',
        'maxLength',
        'equals',
        'notEquals',
        'lengthEquals',
        'matches',
        'isCpf',
        'isCnpj',
        'isEmail',
        'isUrl',
      ],
      'Date': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
        'isLessThanCurrentDate',
        'isLessThanOrEqualToCurrentDate',
        'isGreaterThanCurrentDate',
        'isGreaterThanOrEqualToCurrentDate',
        'isLessThanCurrentDateMinusDays',
        'isLessThanOrEqualToCurrentDateMinusDays',
        'isGreaterThanCurrentDatePlusDays',
        'isGreaterThanOrEqualToCurrentDatePlusDays',
      ],
      'Time': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
        'isLessThanCurrentTime',
        'isLessThanOrEqualToCurrentTime',
        'isGreaterThanCurrentTime',
        'isGreaterThanOrEqualToCurrentTime',
        'isLessThanCurrentTimeMinusSeconds',
        'isLessThanOrEqualToCurrentTimeMinusSeconds',
        'isGreaterThanCurrentTimePlusSeconds',
        'isGreaterThanOrEqualToCurrentTimePlusSeconds',
        'isLessThanCurrentTimeMinusMinutes',
        'isLessThanOrEqualToCurrentTimeMinusMinutes',
        'isGreaterThanCurrentTimePlusMinutes',
        'isGreaterThanOrEqualToCurrentTimePlusMinutes',
        'isLessThanCurrentTimeMinusHours',
        'isLessThanOrEqualToCurrentTimeMinusHours',
        'isGreaterThanCurrentTimePlusHours',
        'isGreaterThanOrEqualToCurrentTimePlusHours',
      ],
      'DateTime': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo', //ok
        'isLessThanCurrentDateTime',
        'isLessThanOrEqualToCurrentDateTime', //ok
        'isGreaterThanCurrentDateTime',
        'isGreaterThanOrEqualToCurrentDateTime', //ok
        'isLessThanCurrentDateTimeMinusSeconds',
        'isLessThanOrEqualToCurrentDateTimeMinusSeconds',
        'isGreaterThanCurrentDateTimePlusSeconds',
        'isGreaterThanOrEqualToCurrentDateTimePlusSeconds', //ok
        'isLessThanCurrentDateTimeMinusMinutes',
        'isLessThanOrEqualToCurrentDateTimeMinusMinutes',
        'isGreaterThanCurrentDateTimePlusMinutes',
        'isGreaterThanOrEqualToCurrentDateTimePlusMinutes', //ok
        'isLessThanCurrentDateTimeMinusHours',
        'isLessThanOrEqualToCurrentDateTimeMinusHours',
        'isGreaterThanCurrentDateTimePlusHours',
        'isGreaterThanOrEqualToCurrentDateTimePlusHours',
        'isLessThanCurrentDateTimeMinusDays',
        'isLessThanOrEqualToCurrentDateTimeMinusDays',
        'isGreaterThanCurrentDateTimePlusDays',
        'isGreaterThanOrEqualToCurrentDateTimePlusDays',
      ],
    };
    return conditionsMap[dataType] ?? [];
  }

  static List<String> conditionsForEntity(String dataType) {
    final conditionsMap = {
      'list': [
        'isEmpty',
        'isNotEmpty',
        'lengthEquals',
        'lengthNotEquals',
        'lengthLessThan',
        'lengthLessThanOrEqualTo',
        'lengthGreaterThan',
        'lengthGreaterThanOrEqualTo',
      ],
      'listOfEntities': [
        'isEmpty',
        'isNotEmpty',
        'lengthEquals',
        'lengthNotEquals',
        'lengthLessThan',
        'lengthLessThanOrEqualTo',
        'lengthGreaterThan',
        'lengthGreaterThanOrEqualTo',
      ],
      'bool': ['isTrue', 'isFalse'],
      'short/int16': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
      ],
      'byte/int8': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
      ],
      'int/int32': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
      ],
      'long/int64': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
      ],
      'double/float64': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
      ],
      'float/float32': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
      ],
      'BigDecimal': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
      ],
      'String': ['equals', 'notEquals'],
      'Date': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
        'isLessThanCurrentDate',
        'isLessThanOrEqualToCurrentDate',
        'isGreaterThanCurrentDate',
        'isGreaterThanOrEqualToCurrentDate',
        'isLessThanCurrentDateMinusDays',
        'isLessThanOrEqualToCurrentDateMinusDays',
        'isGreaterThanCurrentDatePlusDays',
        'isGreaterThanOrEqualToCurrentDatePlusDays',
        'isLessThanCurrentDateMinusMonths',
        'isLessThanOrEqualToCurrentDateMinusMonths',
        'isGreaterThanCurrentDatePlusMonths',
        'isGreaterThanOrEqualToCurrentDatePlusMonths',
        'isLessThanCurrentDateMinusYears',
        'isLessThanOrEqualToCurrentDateMinusYears',
        'isGreaterThanCurrentDatePlusYears',
        'isGreaterThanOrEqualToCurrentDatePlusYears',
      ],
      'Time': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
        'isLessThanCurrentTime',
        'isLessThanOrEqualToCurrentTime',
        'isGreaterThanCurrentTime',
        'isGreaterThanOrEqualToCurrentTime',
        'isLessThanCurrentTimeMinusSeconds',
        'isLessThanOrEqualToCurrentTimeMinusSeconds',
        'isGreaterThanCurrentTimePlusSeconds',
        'isGreaterThanOrEqualToCurrentTimePlusSeconds',
        'isLessThanCurrentTimeMinusMinutes',
        'isLessThanOrEqualToCurrentTimeMinusMinutes',
        'isGreaterThanCurrentTimePlusMinutes',
        'isGreaterThanOrEqualToCurrentTimePlusMinutes',
        'isLessThanCurrentTimeMinusHours',
        'isLessThanOrEqualToCurrentTimeMinusHours',
        'isGreaterThanCurrentTimePlusHours',
        'isGreaterThanOrEqualToCurrentTimePlusHours',
      ],
      'DateTime': [
        'isEqualTo',
        'isNotEqualTo',
        'isLessThan',
        'isLessThanOrEqualTo',
        'isGreaterThan',
        'isGreaterThanOrEqualTo',
        'isLessThanCurrentDateTime',
        'isLessThanOrEqualToCurrentDateTime',
        'isGreaterThanCurrentDateTime',
        'isGreaterThanOrEqualToCurrentDateTime',
        'isLessThanCurrentTimeMinusSeconds',
        'isLessThanOrEqualToCurrentTimeMinusSeconds',
        'isGreaterThanCurrentTimePlusSeconds',
        'isGreaterThanOrEqualToCurrentTimePlusSeconds',
        'isLessThanCurrentTimeMinusMinutes',
        'isLessThanOrEqualToCurrentTimeMinusMinutes',
        'isGreaterThanCurrentTimePlusMinutes',
        'isGreaterThanOrEqualToCurrentTimePlusMinutes',
        'isLessThanCurrentTimeMinusHours',
        'isLessThanOrEqualToCurrentTimeMinusHours',
        'isGreaterThanCurrentTimePlusHours',
        'isGreaterThanOrEqualToCurrentTimePlusHours',
        'isLessThanCurrentDateMinusDays',
        'isLessThanOrEqualToCurrentDateMinusDays',
        'isGreaterThanCurrentDatePlusDays',
        'isGreaterThanOrEqualToCurrentDatePlusDays',
        'isLessThanCurrentDateMinusMonths',
        'isLessThanOrEqualToCurrentDateMinusMonths',
        'isGreaterThanCurrentDatePlusMonths',
        'isGreaterThanOrEqualToCurrentDatePlusMonths',
        'isLessThanCurrentDateMinusYears',
        'isLessThanOrEqualToCurrentDateMinusYears',
        'isGreaterThanCurrentDatePlusYears',
        'isGreaterThanOrEqualToCurrentDatePlusYears',
      ],
    };
    return conditionsMap[dataType] ?? [];
  }
}
